name = "fisher"
description = "Personal theme for my Zola blog."
min_version = "0.19.2"
license = "MIT"
homepage = "https://github.com/kstr0git/fisher"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

[author]
name = "kstr0"
homepage = "https://github.com/kstr0git"
